import os

import pandas as pd
import streamlit as st

from pathlib import PosixPath
from datetime import datetime
from pymongo import MongoClient # Local testing
from pymongo.server_api import ServerApi # Deploy server

class database():
    """
    Database operations handling
    """
    # Initialisation
    #####################################################
    def __init__(self):
        # Variables
        self._client = None
        self._db = None
        self._history = None
        self._parameters = None
        self._results = None
        self._statusMap = {
            0: "Submited",
            1: "Running",
            2: "Completed",
            3: "Error"
        }
        # Client connection
        self._connect_client()

        # Instantiate database
        self._init_database()

    def _connect_client(self):
        ## Local
        uri = "mongodb://localhost:27017/"
        self._client = MongoClient(uri)
        ## Atlas
        """
        uri = f"mongodb+srv://{st.secrets.database['username']}:{st.secrets.database['password']}@{st.secrets.database['cluster']}"
        self.client = MongoClient(uri, server_api=ServerApi(version="1", strict=True, deprecation_errors=True))
        """

    def _disconnect_client(self):
        self._client.close()

    def _init_database(self) -> None:
        """
        Instantiate the database & collections
        """
        # Database
        self._db = self._client['phyml']
        # Collections
        collections = self._db.list_collection_names()
        ## Runs history
        if "history" not in collections:
            self._history = self._db.create_collection("history")
        else:
            self._history = self._db["history"]
        ## Runs parameters
        if "parameters" not in collections:
            self._parameters = self._db.create_collection("parameters")
        else:
            self._parameters = self._db["parameters"]
        ## Runs results
        if "results" not in collections:
            self._results = self._db.create_collection("results")
        else:
            self._results = self._db["results"]

    # Public functions
    #####################################################

    # Insert data
    def new_run(self):
        id = self._add_history(
            datetime.now()
        )
        return id
    
    def insert_run_parameters(self, id, config):
        self._add_parameters(id, config)
    
    def new_results(self, id):
        self._add_results(id)

    # Get data
    def get_runs_history(self):
        self._get_history()
        self._get_parameters()

    def get_run_results(self, id):
        self._get_results()

    # Private functions
    #####################################################

    # Setters
    def _add_history(self, startTime):

        record = {
            # "_id": , # Generated by MongoDB
            "Status": self._statusMap[0],
            "StartTime": startTime,
            "EndTime": None,
        }
        rec = self._history.insert_one(record)
        return rec.inserted_id
        
    def _add_parameters(self, id, params):
        record = {
            "_id": id,
            "input": params['input'],
            "datatype": params['datatype'],
            "sequential": params['sequential'],
            "multiple": params['multiple'],
            "pars": params['pars'],
            "bootstrap": params['bootstrap'],
            "model": params['model'],
            "equilibrium": params['equilibrium'],
            "ts/tv": params['ts/tv'],
            "pinv": params['pinv'],
            "nclasses": params['nclasses'],
            "alpha": params['alpha'],
            "search": params['search'],
            "params": params['params'],
            "rand_start": params['rand_start'] if params['search'] == "SPR" else None,
            "n_rand_starts": params['n_rand_starts'] if params['search'] == "SPR" else None
        }
        self._parameters.insert_one(record)

# TODO: Insert results after testing phyml
    def _add_results(self, id, results):
        record = {
            "_id": id,
        }
        self._results.insert_one(record)

    def _update_status(self, id, status: int):
        query = {"_id": id}
        update = {
            "$set":
                {"Status": status}
        }
        self._history.update_one(query, update)

    # Getters
    def _get_history(self, id):
        query = {"_id": id}
        return self._history.find(query)
    
    def _get_parameters(self, id):
        query = {"_id": id}
        return self._parameters.find(query)

    def _get_results(self, id):
        query = {"_id": id}
        return self._results.find(query)